In [1]:
import os
import pandas as pd
# path = "/data/home/homefun/weights"
path = "/devdata/home/homefun/weights"

In [2]:
def filterCsv(csv, num):
    csv.sort_values(by='f', ascending=False, inplace=True)
    # print(csv[['index', 'con']])
    print(len(csv))
    return csv['index'].head(num)

In [3]:
def show(path_list, index = -1, colum = -1, num = -1):
    record = pd.DataFrame()
    csv_list = []
    for p in path_list:
        csv = pd.read_csv(os.path.join(p, 'record.csv'))
        csv['con'] = csv['insert_mean'] - csv['delete_mean']
        csv['index'] = csv['image_id'] + csv['label'].apply(lambda x : str(x))
        csv_list.append(csv)
    if index != -1:
        csv = csv_list[index[0]]
        csv['f'] = csv_list[index[0]][colum] - csv_list[index[1]][colum]
        fil = filterCsv(csv, num)
        for index, csv in enumerate(csv_list):
            p = path_list[index]
            record[p.split('/')[-3] + "_" + p.split('/')[-2]] = \
                csv.loc[csv['index'].isin(fil), ['delete_mean', 'insert_mean', 'con', 'drop', 'increase', 'hits', 'loc']].describe().loc['mean', :]
    else:
        for index, csv in enumerate(csv_list):
            p = path_list[index]
            record[p.split('/')[-3] + "_" + p.split('/')[-2]] = \
                csv.loc[:, ['delete_mean', 'insert_mean', 'con', 'drop', 'increase', 'hits', 'loc']].describe().loc['mean', :]
    return record.T

In [4]:
def show_one(path):
    csv = pd.read_csv(os.path.join(path, 'record.csv'))
    return csv

In [5]:
def concat(save_path):
    path_list = []
    for p in os.listdir(save_path):
        if p[-3:] == 'csv':
            path_list.append(os.path.join(save_path, p))
    if len(path_list) != 1:
        csv = pd.DataFrame()
        for p in path_list:
            try:
                csv_ = pd.read_csv(p)
                csv_.index = list(range(len(csv_)))
                csv = pd.concat([csv, csv_], ignore_index=True)
                csv.index = list(range(len(csv)))
            except Exception:
                pass
        csv.to_csv(os.path.join(save_path, 'record.csv'), index=False)

In [6]:
# path_list = [   
#                 # r"CAM/mgradcam/4/202502281039",
#                 r"CAM/mgradcam/4/202312031459",
#                 # r"CAM/mgradcam/4/202312062043"
#                 r"CAM/eigengradcam/4/202509041050",
#                 r"CAM/mgradcam/432/202312062046",
#                 # r"CAM/finercam/4/202508271635",
#                 r"CAM/xgradcam/4/202508311748",   
#                 r"CAM/xgradcam/4/202508311748",   
#                 
#             ]
# path_list = [os.path.join(path, p) for p in path_list]
# record = show(path_list)
# record

In [6]:
# 4
# all
path_list = [   
              r"CAM/gradcam/4/202312022200",
    
              r"CAM/gradcam/2/202607151713",
              r"CAM/gradcam/3/202607151714",
    
              r"CAM/gradcam++/4/202312022201",
              r"CAM/layercam/4/202312022202",
              r"CAM/fullgrad/4/202312031544",               
              # r"CAM/mgradcam/4/202312062043",
              r"CAM/mgradcam/4/202511201012",
    
              r"CAM/mgradcam/2/202607161628",
              r"CAM/mgradcam/3/202607151853",    
    
              r"CAM/finercam/4/202511281415",
              # r"CAM/mgradcam/432/202312062046",
              r"CAM/mgradcam/432/202511191655",
              # r"CAM/mgradcam/432/202511201108",
              r"CAM/scorecam/4/202509172029",
              r"CAM/ablationcam/4/202312041341", 
              # r"CAM/xgradcam/4/202508311748", 
              # r"CAM/xgradcam/4/202509191026", 
              # r"CAM/eigengradcam/4/202509041050",    
              # r"CAM/eigencam/4/202509171726",    
              # r"CAM/eigengradcam/4/202512011345",    
              r"CAM/kpcacam/4/202509171449",    
              # r"CAM/kpcacam/4/202512011139",    
              # r"CAM/aligngradcam/4/202510171421",    
              # r"CAM/aligngradcam/4/202510171543",
              # r"CAM/aligngradcam/4/202511181057",    
              # r"CAM/aligngradcam/4/202510171659",    
              # r"CAM//aligngradcam/4/202510172131",    
              # r"CAM/aligngradcam/4/202510162149",      
              # r"CAM/aligngradcam/4/202510170908",      
              # r"CAM/aligngradcam/432/202510171109",      
              r"CAM/mgradcam/43/202512011950",      
              r"CAM/mgradcam/42/202512012035",      
              r"CAM/mgradcam/32/202602252125",  
    
              # 【28】
              # r"CAM_VGG/mgradcam/VGG_543/202602261015",   
              # r"CAM_VGG/gradcam/VGG_5/202602261712",   
              # r"CAM_VGG/mgradcam/VGG_542/202602261841",   
              # 【all】
              r"CAM_VGG/gradcam/VGG_5/202602261022", 
              r"CAM_VGG/mgradcam/VGG_543/202602261117",    
              r"CAM_VGG/mgradcam/VGG_542/202602261544",   
              r"CAM_VGG/mgradcam/VGG_532/202602261631",   
              r"CAM_VGG/mgradcam/VGG_5432/202602261851",   
              r"CAM_VGG/mgradcam/VGG_54/202602261929", 
              r"CAM_VGG/mgradcam/VGG_53/202602262008", 
              r"CAM_VGG/mgradcam/VGG_52/202602262008",   
              # r"CAM_efficientNet/efficientnet_b0/gradcam/4/202602261442",   
            ]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [3, 1], 'con', 4000)
record

3546

,delete_mean,insert_mean,con,drop,increase,hits,loc
gradcam_4,0.234918,0.697728,0.462809,0.020218,0.395375,0.578325,0.598834
gradcam_2,0.218017,0.538345,0.320328,0.257053,0.272138,0.413805,0.423687
gradcam_3,0.198724,0.681577,0.482853,0.084066,0.362098,0.517250,0.547131
gradcam++_4,0.229189,0.693321,0.464131,0.076067,0.388889,0.576803,0.574675
layercam_4,0.234611,0.686443,0.451832,0.086706,0.370840,0.568932,0.561721
fullgrad_4,0.252354,0.657768,0.405415,0.107087,0.309363,0.523660,0.480338
mgradcam_4,0.226195,0.705275,0.479080,0.055050,0.425832,0.578937,0.584622
mgradcam_2,0.196966,0.552624,0.355657,0.270795,0.283982,0.414000,0.378752
mgradcam_3,0.181358,0.683195,0.501837,0.121059,0.411168,0.460335,0.410499
finercam_4,0.244951,0.626913,0.381963,0.083379,0.377609,0.455601,0.470698
mgradcam_432,0.202084,0.713850,0.511766,0.054981,0.430062,0.589285,0.602791
scorecam_4,0.215437,0.709027,0.493591,0.071383,0.427806,0.562276,0.562554
ablationcam_4,0.273068,0.666043,0.392975,0.176203,0.308235,0.550354,0.555395
kpcacam_4,0.287123,0.631255,0.344132,0.152867,0.267343,0.535692,0.548063
mgradcam_43,0.219318,0.711599,0.492281,0.031240,0.415398,0.588059,0.610265
mgradcam_42,0.216365,0.713336,0.496972,0.032783,0.409475,0.585183,0.605372
mgradcam_32,0.173207,0.685459,0.512252,0.117146,0.413988,0.468142,0.416238
gradcam_VGG_5,0.261874,0.759889,0.498015,0.029962,0.577270,0.555770,0.563759
mgradcam_VGG_543,0.257004,0.773898,0.516894,0.032341,0.613367,0.554739,0.542578
mgradcam_VGG_542,0.251580,0.773295,0.521715,0.034772,0.600959,0.562721,0.554019
mgradcam_VGG_532,0.251716,0.773364,0.521648,0.034390,0.602933,0.562821,0.555940
mgradcam_VGG_5432,0.251576,0.773297,0.521721,0.034772,0.600959,0.562721,0.554019
mgradcam_VGG_54,0.256970,0.772922,0.515952,0.031479,0.614777,0.555292,0.547084
mgradcam_VGG_53,0.257200,0.772890,0.515690,0.031473,0.614495,0.555193,0.546793
mgradcam_VGG_52,0.251635,0.773143,0.521508,0.033989,0.597857,0.562866,0.557825

In [8]:
path_list = [   
                r"CAM/gradcam/4/202312022200",                
                # r"CAM/mgradcam/432/202511191655",
                r"CAM/mgradcam/4/202511201012",
                # r"CAM/mgradcam/432_softmax/202603021052",
                r"CAM/mgradcam/4_softmax/202603021137",
                # r"CAM/mgradcam/432_Z-score/202603021338",
                r"CAM/mgradcam/4_Z-score/202603021256",
            ]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list)
record

,delete_mean,insert_mean,con,drop,increase,hits,loc
gradcam_4,0.234918,0.697728,0.462809,0.020218,0.395375,0.578325,0.598834
mgradcam_4,0.226195,0.705275,0.479080,0.055050,0.425832,0.578937,0.584622
mgradcam_4_softmax,0.234912,0.697698,0.462786,0.020530,0.384377,0.578335,0.598844
mgradcam_4_Z-score,0.227960,0.694884,0.466924,0.073546,0.390017,0.576021,0.575823

In [9]:
# # 432
# path_list = [   
#               r"CAM/gradcam/432/202312021429",
#               r"CAM/gradcam++/432/202312021429",
#               r"CAM/layercam/432/202312021430",
#               # r"CAM/mgradcam/432/202312062046",
#               r"CAM/mgradcam/432/202511191655",
#               r"CAM/scorecam/432/202312051454",
#               r"CAM/ablationcam/432/202312041345",
#               r"CAM/xgradcam/432/202509011051",
#               # r"CAM/eigengradcam/432/202509020906",
#               r"CAM/eigencam/432/202509171850",
#               r"CAM/kpcacam/432/202509171602",
#               r"CAM/finercam/432/202508272108",
#               r"CAM/mgradcam/43/202509191215",
#               r"CAM/mgradcam/42/202509191342",
#             ]
# path_list = [os.path.join(path, p) for p in path_list]
# record = show(path_list, [3, 1], 'con', 4000)
# record

In [10]:
# # 4
# # all
# path_list = [   
#               r"CAM/gradcam/4/202312022200",
#               r"CAM/gradcam++/4/202312022201",
#               r"CAM/layercam/4/202312022202",
#               r"CAM/fullgrad/4/202312031544",               
#               r"CAM/mgradcam/4/202312062043",
#               r"CAM/finercam/4/202508271902",
#               r"CAM/mgradcam/432/202312062046",
#               r"CAM/scorecam/4/202312041339",
#               r"CAM/ablationcam/4/202312041341", 
#               r"CAM/xgradcam/4/202508311748", 
#               r"CAM/eigengradcam/4/202509011915",    
#               r"CAM/mgradcam/43/202509191215",
#               r"CAM/mgradcam/42/202509191342",
#             ]
# path_list = [os.path.join(path, p) for p in path_list]
# record = show(path_list)
# record

In [7]:
# CoCo-compere
# 4
# all
path_list = [
    # r"COCO_CAM/mgradcam/432/202509091020",
    # r"COCO_CAM/mgradcam/432/202511241649",
    r"COCO_CAM/mgradcam/432/202511262312",
    # r"COCO_CAM/mgradcam/432/202511261108",
    # r"COCO_CAM/mgradcam/4/202511211119",
    r"COCO_CAM/mgradcam/4/202511262311",
    
    r"COCO_CAM/mgradcam/2/202607161715",
    r"COCO_CAM/mgradcam/3/202607161645",
    
    # r"COCO_CAM/gradcam/4/202509091029",
    r"COCO_CAM/fullgrad/4/202511271844",
    r"COCO_CAM/gradcam/4/202511261122",
    
    r"COCO_CAM/gradcam/2/202607141258",
    r"COCO_CAM/gradcam/3/202607132311",    
    
    r"COCO_CAM/gradcam++/4/202511270930",
    r"COCO_CAM/layercam/4/202511270925",
    r"COCO_CAM/ablationcam/4/202511271729",
    # r"COCO_CAM/eigengradcam/4/202511291111",
    # r"COCO_CAM/eigencam/4/202512010001",
    r"COCO_CAM/finercam/4/202511281154",
    # r"COCO_CAM/mgradcam/432/202511251525",
    # r"COCO_CAM/mgradcam/43/202512012155",
    # r"COCO_CAM/mgradcam/42/202512021359",    
    # r"COCO_CAM/mgradcam/43/202512012155",
    r"COCO_CAM/mgradcam/43/202603022137",
    # r"COCO_CAM/mgradcam/42/202512021359",
    r"COCO_CAM/mgradcam//42/202602260958",
    r"COCO_CAM/mgradcam/32/202602252337",
    # r"COCO_CAM/gradcam/4/202511251523",
    # r"COCO_CAM/layercam/4/202511251638",
    # r"COCO_CAM/fullgrad/4/202511251647",
]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [1, 0], 'con', 80000)
record

71530

,delete_mean,insert_mean,con,drop,increase,hits,loc
mgradcam_432,0.164038,0.473518,0.309480,0.133190,0.454467,0.314497,0.332881
mgradcam_4,0.169715,0.469087,0.299371,0.134396,0.454285,0.307311,0.319886
mgradcam_2,0.146873,0.308210,0.161338,0.434956,0.250189,0.222292,0.203057
mgradcam_3,0.170976,0.386725,0.215749,0.317063,0.332001,0.239053,0.213242
fullgrad_4,0.084644,0.249493,0.164849,0.561504,0.185083,0.255291,0.260653
gradcam_4,0.168378,0.464356,0.295978,0.065754,0.229386,0.312437,0.333995
gradcam_2,0.133252,0.375516,0.242264,0.215513,0.131693,0.229043,0.237717
gradcam_3,0.139569,0.411894,0.272325,0.214772,0.232098,0.267863,0.287730
gradcam++_4,0.189309,0.442350,0.253041,0.189047,0.419698,0.286150,0.271479
layercam_4,0.191460,0.439960,0.248500,0.192463,0.414372,0.283842,0.268249
ablationcam_4,0.255719,0.379296,0.123578,0.362555,0.292814,0.263044,0.268274
finercam_4,0.188462,0.440353,0.251891,0.156234,0.338585,0.273707,0.284596
mgradcam_43,0.167184,0.471560,0.304375,0.131200,0.448176,0.312375,0.329517
_42,0.166649,0.471975,0.305326,0.133367,0.454355,0.310002,0.324733
mgradcam_32,0.170047,0.385002,0.214956,0.316263,0.325293,0.244782,0.218496

In [12]:
# CoCo-compere small/medium/large
# test
path_list = [
    r"COCO_CAM/mgradcam/432/202511262312",
    r"COCO_CAM/gradcam/4/202511261122",
    
    # 按照单个边框面积大小划分
    # large
    r"COCO_CAM_splitSize/mgradcam/large_432/202602281506",
    r"COCO_CAM_splitSize/gradcam/large_4/202602281519",
    
    # medium
    r"COCO_CAM_splitSize/mgradcam/medium_432/202602281533",
    r"COCO_CAM_splitSize/gradcam/medium_4/202602281527",

    # small
    r"COCO_CAM_splitSize/mgradcam/small_432/202602281546",
    r"COCO_CAM_splitSize/gradcam/small_4/202602281554",

    # 按照整体面积大小划分数据集
    # large
    # r"COCO_CAM_splitSize/mgradcam/large_432/202602281608",
    # r"COCO_CAM_splitSize/gradcam/large_4/202602281623",
    
    # # medium
    # r"COCO_CAM_splitSize/mgradcam/medium_432/202602281641",
    # r"COCO_CAM_splitSize/gradcam/medium_4/202602281635",
    # 
    # # medium
    # r"COCO_CAM_splitSize/mgradcam/small_432/202602281607",
    # r"COCO_CAM_splitSize/gradcam/small_4/202602281605",
]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [6, 0], 'con', 80000)
record

20119

,delete_mean,insert_mean,con,drop,increase,hits,loc
mgradcam_432,0.164171,0.41866,0.254489,0.142043,0.473383,0.137623,0.146723
gradcam_4,0.171225,0.40798,0.236756,0.071927,0.226850,0.135985,0.146011
mgradcam_large_432,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.442297
gradcam_large_4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.446428
mgradcam_medium_432,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.090465
gradcam_medium_4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.088344
mgradcam_small_432,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.013364
gradcam_small_4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.012587

In [9]:
# Exdark-compere
# 4
# all
path_list = [   
              
              # r"Exdark_CAM/mgradcam/432/202509111611",
              # r"Exdark_CAM/mgradcam/432/202511201020",
              r"Exdark_CAM/mgradcam/432/202511210959",
              r"Exdark_CAM/fullgrad/4/202509121018",  
              # r"Exdark_CAM/mgradcam/432/202509180539",
              # r"Exdark_CAM/gradcam/4/202509111747",  
              # r"Exdark_CAM/gradcam/4/202509111634",  
              r"Exdark_CAM/gradcam/4/202511210005",  
    
              r"Exdark_CAM/gradcam/2/202607132243",  
              r"Exdark_CAM/gradcam/3/202607132212",  
    
              r"Exdark_CAM/gradcam++/4/202509120006",  
              r"Exdark_CAM/layercam/4/202509120123",  
              r"Exdark_CAM/scorecam/4/202509130629",
              r"Exdark_CAM/ablationcam/4/202509120323",  
              # r"Exdark_CAM/xgradcam/4/202509121630",  
              # r"Exdark_CAM/eigencam/4/202509121824", 
              r"Exdark_CAM/kpcacam/4/202509122037", 
              # r"Exdark_CAM/kpcacam/4/202512011111", 
              # r"Exdark_CAM/kpcacam/4/202512011428", 
              # r"Exdark_CAM/eigengradcam/4/202509120209",  
              r"Exdark_CAM/finercam/4/202512010021",  
              # r"Exdark_CAM/mgradcam/4/202509111656",  
              r"Exdark_CAM/mgradcam/4/202511211023",  
    
              r"Exdark_CAM/mgradcam/2/202607151937",  
              r"Exdark_CAM/mgradcam/3/202607151937",  
    
              r"Exdark_CAM/mgradcam/43/202512011851",  
              r"Exdark_CAM/mgradcam/42/202512011914",  
              r"Exdark_CAM/mgradcam/32/202602252124",  
              # r"Exdark_CAM/mgradcam/4/202512011510",  
              # r"Exdark_CAM/mgradcam/4/202509180450",  
    
            ]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [0, 2], 'con', 2500)
# record = show(path_list)
record

2419

,delete_mean,insert_mean,con,drop,increase,hits,loc
mgradcam_432,0.203077,0.657305,0.454228,0.080651,0.415048,0.419293,0.456838
fullgrad_4,0.258981,0.595020,0.336039,0.196170,0.279041,0.348388,0.317965
gradcam_4,0.236220,0.644503,0.408283,0.049228,0.392724,0.409901,0.442023
gradcam_2,0.275367,0.538634,0.263266,0.275522,0.315420,0.258537,0.270642
gradcam_3,0.217750,0.628719,0.410968,0.136796,0.409260,0.334711,0.370864
gradcam++_4,0.236202,0.628409,0.392208,0.149488,0.354692,0.403274,0.412872
layercam_4,0.242833,0.620661,0.377828,0.162365,0.334849,0.395148,0.400398
scorecam_4,0.233787,0.640441,0.406654,0.133147,0.393551,0.382459,0.388639
ablationcam_4,0.269552,0.614325,0.344772,0.226681,0.307565,0.379953,0.396268
kpcacam_4,0.253768,0.636164,0.382396,0.053335,0.349731,0.388256,0.418678
finercam_4,0.261268,0.605789,0.344521,0.130050,0.358826,0.335799,0.361553
mgradcam_4,0.226618,0.649065,0.422447,0.081866,0.403473,0.409211,0.436163
mgradcam_2,0.249544,0.556793,0.307249,0.312288,0.353038,0.254738,0.224862
mgradcam_3,0.188917,0.630637,0.441720,0.196346,0.414221,0.288231,0.250294
mgradcam_43,0.215035,0.654815,0.439779,0.080233,0.417115,0.415702,0.449458
mgradcam_42,0.209400,0.653010,0.443609,0.079634,0.417528,0.412218,0.442909
mgradcam_32,0.185891,0.636709,0.450818,0.194234,0.417941,0.293304,0.254673

In [14]:
# # Exdark-compere
# # 432
# # all
# path_list = [   
#               # r"Exdark_CAM/mgradcam/432/202509111611",
#               r"Exdark_CAM/mgradcam/432/202511201020",
#               # r"Exdark_CAM/gradcam/432/202509111919",
#               r"Exdark_CAM/gradcam/432/202511210004",
#               r"Exdark_CAM/gradcam++/432/202509120023",  
#               r"Exdark_CAM/layercam/432/202509120140",  
#               r"Exdark_CAM/ablationcam/432/202509130304",  
#               r"Exdark_CAM/scorecam/432/202509130856",  
#               r"Exdark_CAM/xgradcam/432/202509121731",  
#               r"Exdark_CAM/eigengradcam/432/202509120234",  
#               r"Exdark_CAM/finercam/432/202509120101",  
#               r"Exdark_CAM/eigencam/432/202509121923",  
#               r"Exdark_CAM/kpcacam/432/202509122257",  
#               r"Exdark_CAM/mgradcam/43/202509221424",  
#               r"Exdark_CAM/mgradcam/42/202509220946",   
#             ]
# path_list = [os.path.join(path, p) for p in path_list]
# record = show(path_list, [0, 1], 'con', 2500)
# # record = show(path_list)
# record

In [15]:
# # Exdark-compere
# # 432
# # all
# path_list = [
#     # r"Exdark_CAM/mgradcam/432/202509111611",
#     # r"Exdark_CAM/gradcam/432/202509111919",
#     # r"Exdark_CAM/gradcam++/432/202509120023",
#     # r"Exdark_CAM/layercam/432/202509120140",
#     # r"Exdark_CAM/ablationcam/432/202509130304",
#     # r"Exdark_CAM/scorecam/432/202509130856",
#     # r"Exdark_CAM/xgradcam/432/202509121731",
#     # r"Exdark_CAM/eigengradcam/432/202509120234",
#     # r"Exdark_CAM/finercam/432/202509120101",
#     # r"Exdark_CAM/mgradcam/42/202509191624", 
#     # r"Exdark_CAM/eigencam/432/202509121923",
#     # r"Exdark_CAM/kpcacam/432/202509122257",
#     # r"Exdark_CAM/mgradcam/43/202509191532",
#     r"Exdark_CAM/mgradcam/42/202509202224",
# ]
# path_list = [os.path.join(path, p) for p in path_list]
# record = show(path_list)
# # record = show(path_list)
# record

In [16]:
# 4
# all
path_list = [      
              r"CAM_efficientNet/efficientnet_b0/gradcam/4/202602261442",   
              r"CAM_efficientNet/efficientnet_b0/mgradcam/432/202602261515",   
            ]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list)
record

,delete_mean,insert_mean,con,drop,increase,hits,loc
gradcam_4,0.511385,0.781828,0.270443,0.028932,0.631980,0.533901,0.528023
mgradcam_432,0.504189,0.775614,0.271425,0.025929,0.618161,0.537432,0.533647

In [17]:
# 4 VOC_VGG
# all
path_list = [ r"CAM_VGG/gradcam/VGG_5/202602261022", 
              r"CAM_VGG/gradcam++/VGG_5/202602262155", 
              r"CAM_VGG/layercam/VGG_5/202602262228", 
              r"CAM_VGG/ablationcam/VGG_5/202602262302", 
              r"CAM_VGG/finercam/VGG_5/202602262341", 
              r"CAM_VGG/kpcacam/VGG_5/202602271140", 
              r"CAM_VGG/scorecam/VGG_5/202602271304", 
              r"CAM_VGG/fullgrad/VGG_5/202602271448", 
              r"CAM_VGG/mgradcam/VGG_5/202602262109", 
              # [21]+[9]
              # r"CAM_VGG/mgradcam/VGG_543/202602261117",   
              # [23]+[9]
              r"CAM_VGG/mgradcam/VGG_543/202603071105",   
              # [21]+[9]
              # r"CAM_VGG/mgradcam/VGG_542/202602261544",    
              # [23]+[9]
              r"CAM_VGG/mgradcam/VGG_542/202603062154",   
              r"CAM_VGG/mgradcam/VGG_532/202602261631",   
              r"CAM_VGG/mgradcam/VGG_5432/202602261851",   
              r"CAM_VGG/mgradcam/VGG_54/202602261929", 
              r"CAM_VGG/mgradcam/VGG_53/202602262008", 
              r"CAM_VGG/mgradcam/VGG_52/202602262008",    
            ]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [3, 1], 'con', 4000)
record

3546

,delete_mean,insert_mean,con,drop,increase,hits,loc
gradcam_VGG_5,0.261874,0.759889,0.498015,0.029962,0.577270,0.555770,0.563759
gradcam++_VGG_5,0.295316,0.731130,0.435814,0.059856,0.476311,0.529498,0.492179
layercam_VGG_5,0.253578,0.769631,0.516053,0.024905,0.622955,0.525964,0.497291
ablationcam_VGG_5,0.316588,0.705685,0.389097,0.181186,0.429780,0.518897,0.521100
finercam_VGG_5,0.263107,0.735192,0.472085,0.052105,0.524253,0.495937,0.499224
kpcacam_VGG_5,0.262749,0.740309,0.477560,0.017160,0.443316,0.573111,0.611074
scorecam_VGG_5,0.254904,0.767528,0.512624,0.039200,0.510716,0.562271,0.564652
fullgrad_VGG_5,0.312307,0.681114,0.368806,0.124756,0.334461,0.480751,0.444849
mgradcam_VGG_5,0.257197,0.772888,0.515691,0.031473,0.614495,0.555193,0.546793
mgradcam_VGG_543,0.240048,0.777745,0.537697,0.031277,0.623237,0.569627,0.572423
mgradcam_VGG_542,0.242338,0.776524,0.534186,0.032691,0.608291,0.569476,0.572124
mgradcam_VGG_532,0.251716,0.773364,0.521648,0.034390,0.602933,0.562821,0.555940
mgradcam_VGG_5432,0.251576,0.773297,0.521721,0.034772,0.600959,0.562721,0.554019
mgradcam_VGG_54,0.256970,0.772922,0.515952,0.031479,0.614777,0.555292,0.547084
mgradcam_VGG_53,0.257200,0.772890,0.515690,0.031473,0.614495,0.555193,0.546793
mgradcam_VGG_52,0.251635,0.773143,0.521508,0.033989,0.597857,0.562866,0.557825

In [18]:
# 4 ExDark_VGG
# all
path_list = [ r"Exdark_CAM_VGG/mgradcam/VGG_5/202602272011", 
              r"Exdark_CAM_VGG/gradcam/VGG_5/202602272032", 
              # [21]+[9]
              # r"Exdark_CAM_VGG/mgradcam/VGG_542/202602272056", 
              # [23]+[9]
              r"Exdark_CAM_VGG/mgradcam/VGG_542/202603071319",   
              # r"Exdark_CAM_VGG/mgradcam/VGG_653/202602281327",   
              r"Exdark_CAM_VGG/gradcam++/VGG_5/202602272121",   
              r"Exdark_CAM_VGG/layercam/VGG_5/202602272141",   
              r"Exdark_CAM_VGG/ablationcam/VGG_5/202602272202",   
              r"Exdark_CAM_VGG/finercam/VGG_5/202602272225",   
              r"Exdark_CAM_VGG/kpcacam/VGG_5/202602280030",   
              r"Exdark_CAM_VGG/scorecam/VGG_5/202602280123",   
              r"Exdark_CAM_VGG/fullgrad/VGG_5/202602280215",  
              # [21]+[14]
              # r"Exdark_CAM_VGG/mgradcam/VGG_543/202602272246",  
              # [23]+[16]
              r"Exdark_CAM_VGG/mgradcam/VGG_543/202603071224",   
              
              r"Exdark_CAM_VGG/mgradcam/VGG_532/202602272320",   
              r"Exdark_CAM_VGG/mgradcam/VGG_5432/202602272354",   
              r"Exdark_CAM_VGG/mgradcam/VGG_54/202602281045", 
              r"Exdark_CAM_VGG/mgradcam/VGG_53/202602281110", 
              r"Exdark_CAM_VGG/mgradcam/VGG_52/202602281145",    
            ]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [0, 2], 'con', 2500)
# record = show(path_list)
record

2419

,delete_mean,insert_mean,con,drop,increase,hits,loc
mgradcam_VGG_5,0.263721,0.702755,0.439034,0.043562,0.643241,0.373658,0.381437
gradcam_VGG_5,0.265696,0.689979,0.424284,0.041145,0.610583,0.369971,0.388116
mgradcam_VGG_542,0.253530,0.715281,0.461751,0.044695,0.628772,0.385814,0.406549
gradcam++_VGG_5,0.290089,0.674235,0.384146,0.069655,0.533278,0.372451,0.351811
layercam_VGG_5,0.269833,0.699230,0.429396,0.049274,0.625052,0.368349,0.353499
ablationcam_VGG_5,0.310744,0.646073,0.335328,0.170488,0.504754,0.347393,0.356773
finercam_VGG_5,0.287965,0.665962,0.377997,0.075134,0.534932,0.344441,0.359743
kpcacam_VGG_5,0.267044,0.675800,0.408756,0.032105,0.493179,0.388244,0.430662
scorecam_VGG_5,0.265548,0.699880,0.434333,0.056411,0.577511,0.370457,0.373256
fullgrad_VGG_5,0.359297,0.633059,0.273762,0.136798,0.368334,0.342975,0.312775
mgradcam_VGG_543,0.251151,0.716324,0.465173,0.044371,0.641587,0.387405,0.409048
mgradcam_VGG_532,0.260502,0.711792,0.451289,0.046623,0.619264,0.377649,0.389715
mgradcam_VGG_5432,0.260116,0.712053,0.451937,0.046628,0.618851,0.377912,0.390596
mgradcam_VGG_54,0.263473,0.703928,0.440455,0.043420,0.643241,0.373912,0.382288
mgradcam_VGG_53,0.263696,0.702777,0.439081,0.043557,0.642828,0.373661,0.381445
mgradcam_VGG_52,0.260543,0.711791,0.451248,0.046567,0.619678,0.377646,0.389707

In [19]:
# 4 COCO_VGG
# all
path_list = [ 
              r"COCO_CAM_VGG/mgradcam/VGG_5/202602281408", 
              # 修改USE_CHANNELS_LAST = True-->false    
              # r"COCO_CAM_VGG/mgradcam/VGG_5/202603071649", 
    
              # r"COCO_CAM_VGG/mgradcam/VGG_5/202603041556", 
              # r"COCO_CAM_VGG/gradcam/VGG_5/202602281405", 
              # 【23+16】修改AUC计算方式，使其更健壮
              r"COCO_CAM_VGG/gradcam/VGG_5/202603071752", 
              # r"COCO_CAM_VGG/gradcam/VGG_5/202603101221", 
              
              # r"COCO_CAM_VGG/gradcam/VGG_5/202603031102", 
              
              # 无
              r"COCO_CAM_VGG/mgradcam/VGG_542/202602282306", 
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603051849", 
              # [28]
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603040940",               
              # [18]
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603040947", 
              # [15]
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603041119",
              # 无无
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603041313", 
              # 4[19] 2[7]
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603041422", 
              # Z-socre
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603041508",  
              # softmax
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603041517", 
              
              # r"COCO_CAM_VGG/mgradcam/VGG_542/202603030942",               
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603032211", 
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603040930", 
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603040930", 
              # 【23+16】
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603050953",  
              # 【23+16】修改AUC计算方式，使其更健壮
              r"COCO_CAM_VGG/mgradcam/VGG_543/202603080203",  
              # r"COCO_CAM_VGG/mgradcam/VGG_543//202603100950",  
              # 【23+18】
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603051955", 
              # 【23+20】
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603060931", 
              # 【23+19】
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603060948", 
              # 【23+17】
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603061023", 
              # 无
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603041323", 
              # 4[15]
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603041328",
              # 3[11]
              # r"COCO_CAM_VGG/mgradcam/VGG_543/202603041336",               
              # 
              # r"COCO_CAM_VGG/mgradcam/VGG_53/202603041347", 
              # r"COCO_CAM_VGG/mgradcam/VGG_52/202603041404", 
                 
              # r"COCO_CAM_VGG/gradcam++/VGG_5/202602282116", 
              # 修改AUC计算方式，使其更健壮
              r"COCO_CAM_VGG/gradcam++/VGG_5/202603081249",
              # r"COCO_CAM_VGG/gradcam++/VGG_5/202603101229",
              # r"COCO_CAM_VGG/ablationcam/VGG_5/202602282314",
              # 修改AUC计算方式，使其更健壮
              r"COCO_CAM_VGG/ablationcam/VGG_5/202603081404",   
              # r"COCO_CAM_VGG/finercam/VGG_5/202603011107", 
              # 修改AUC计算方式，使其更健壮
              r"COCO_CAM_VGG/finercam/VGG_5/202603090848",    
              # r"COCO_CAM_VGG/layercam/VGG_5/202603020929",  
              # 修改AUC计算方式，使其更健壮
              r"COCO_CAM_VGG/layercam/VGG_5/202603082057",  
              # 修改AUC计算方式，使其更健壮
              # r"COCO_CAM_VGG/fullgrad/VGG_5/202603091822",               
            ]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [3, 0], 'insert_mean', 80000)
# record = show(path_list)
record

71530

,delete_mean,insert_mean,con,drop,increase,hits,loc
mgradcam_VGG_5,0.198943,0.499512,0.300568,0.173866,0.445491,0.274238,0.284521
gradcam_VGG_5,0.161545,0.537326,0.375781,0.084148,0.576108,0.297144,0.316665
mgradcam_VGG_542,0.192766,0.484227,0.291462,0.201383,0.414344,0.278362,0.291118
mgradcam_VGG_543,0.154708,0.538839,0.384130,0.120014,0.568754,0.294174,0.309910
gradcam++_VGG_5,0.228111,0.458154,0.230043,0.224308,0.389277,0.240080,0.225003
ablationcam_VGG_5,0.245359,0.462243,0.216883,0.360561,0.333133,0.249774,0.253337
finercam_VGG_5,0.201436,0.488996,0.287560,0.180738,0.492814,0.265197,0.276992
layercam_VGG_5,0.191068,0.502280,0.311212,0.162015,0.493765,0.251866,0.239028

In [20]:
# VGG_CoCo-compere small/medium/large
# test
path_list = [
    r"COCO_CAM_VGG/gradcam/VGG_5/202602281405", 
    r"COCO_CAM_VGG/mgradcam/VGG_542/202602282306", 
    r"COCO_CAM_VGG/mgradcam/VGG_543/202603050953", 
    # r"COCO_CAM_VGG/mgradcam/VGG_5/202602281408", 
    
    # 按照单个边框面积大小划分
    # large
    r"COCO_CAM_splitSize/mgradcam/large_432/202602281506",
    r"COCO_CAM_splitSize/gradcam/large_4/202602281519",
    
    # medium
    r"COCO_CAM_splitSize/mgradcam/medium_432/202602281533",
    r"COCO_CAM_splitSize/gradcam/medium_4/202602281527",

    # small
    r"COCO_CAM_splitSize/mgradcam/small_432/202602281546",
    r"COCO_CAM_splitSize/gradcam/small_4/202602281554",

    # 按照整体面积大小划分数据集
    # large
    # r"COCO_CAM_splitSize/mgradcam/large_432/202602281608",
    # r"COCO_CAM_splitSize/gradcam/large_4/202602281623",
    
    # # medium
    # r"COCO_CAM_splitSize/mgradcam/medium_432/202602281641",
    # r"COCO_CAM_splitSize/gradcam/medium_4/202602281635",
    # 
    # # medium
    # r"COCO_CAM_splitSize/mgradcam/small_432/202602281607",
    # r"COCO_CAM_splitSize/gradcam/small_4/202602281605",
]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [6, 0], 'con', 80000)
# record = show(path_list, [4, 0], 'con', 80000)
# record = show(path_list, [6, 0], 'con', 80000)
record

30368

,delete_mean,insert_mean,con,drop,increase,hits,loc
gradcam_VGG_5,0.201933,0.508790,0.306858,0.123726,0.366010,0.180091,0.202022
mgradcam_VGG_542,0.202033,0.492697,0.290664,0.192171,0.413593,0.176769,0.193178
mgradcam_VGG_543,0.196947,0.503772,0.306825,0.176555,0.431671,0.180727,0.201961
mgradcam_large_432,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.445307
gradcam_large_4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.450435
mgradcam_medium_432,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.084903
gradcam_medium_4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.082104
mgradcam_small_432,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015622
gradcam_small_4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.015093

In [31]:
# 4
# all
path_list = [   
              # r"CAM_MobileNetV2/gradcam/4/202605271507",
              r"CAM_MobileNetV2/gradcam/4/202605271631",
              # r"CAM_MobileNetV2/mgradcam/432/202605271406",
              r"CAM_MobileNetV2/mgradcam/432/202605271600",
            ]
path_list = [os.path.join(path, p) for p in path_list]
record = show(path_list, [1, 0], 'con', 4000)
# record = show(path_list)
record

3546

,delete_mean,insert_mean,con,drop,increase,hits,loc
gradcam_4,0.456297,0.795332,0.339034,0.009769,0.568810,0.572710,0.575123
mgradcam_432,0.411860,0.799860,0.388000,0.012132,0.597011,0.579752,0.578058